### PR TITLE
Track latest semver compatible deps

### PR DESCRIPTION
**Pull request by richard-riverford**
Tweaked dependency version specifiers to track the latest compatible versions of those packages.

### CODE REVIEW

**Comment by mikl** [comment]
@tuananh sorry to bother you, but this fix would be good to get merged.

If you're not interested in maintaining this module any more, I could also take it off your hands.

**Comment by richard-riverford** [comment]
It's great that this has been merged, but we also need to have a new version published to npm, don't we?

**Comment by mikl** [comment]
@richard-riverford you can install it directly from Github by adding something like this to package.json:

```json
  "dependencies": {
    "koa": "^2.7.0",
    "kompression": "github:tuananh/kompression#ab0ae596"
  }
```

**Comment by richard-riverford** [comment]
Yes, true, and in fact that's what I've been doing for a while now to use my patched fork instead of upstream, but doing that breaks tools like `npm outdated`.

**Comment by tuananh** [comment]
new version published

**Pull request merged**
